openapi: 3.0.0
info:
  title: Additional OpenAPI spec for interacting with the Nuts APIs.
  version: 1.0.0

components:
  schemas:
    ID:
      type: string
      description: Identifies the subject of the credential. In other words, the ID of the entity to which the credential was issued. Generally a Nuts DID.
    Organization:
      type: object
      properties:
        "name":
          description: The name of the organization.
          type: string
        "city":
          description: The city of the organization.
          type: string
    NutsOrganizationCredential:
      type: object
      description: The subject of a NutsOrganizationCredential according to the Nuts specs.
      required:
        - "id"
        - "organization"
      properties:
        "id":
          $ref: '#/components/schemas/ID'
        "organization":
          $ref: '#/components/schemas/Organization'
    NutsAuthorizationCredential:
      type: object
      description: The subject of a NutsAuthorizationCredential according to the Nuts specs.
      required:
        - id
        - purposeOfUse
        - subject
      properties:
        "id":
          $ref: '#/components/schemas/ID'
        "purposeOfUse":
          description: Generally an access policy as defined by the Bolt.
          type: string
        "subject":
          type: string
          description: Identifier of the patient (Dutch Social Security Number).
        "resources":
          description: The FHIR resources that can be accessed using the credential.
          type: array
          items:
            $ref: '#/components/schemas/FHIRResource'
    FHIRResource:
      type: object
      required:
        - path
        - operations
      properties:
        "path":
          description: The path of the resource.
          type: string
          example: /Task/1
        "operations":
          description: The FHIR operations that are allowed on the resource.
          type: array
          items:
            type: string
        "userContext":
          description: Indicates whether access to the resource requires an authenticated user.
          type: boolean
        "assuranceLevel":
          description: The assurance level of the credential.
          type: string
          enum:
            - "low"
            - "substantial"
            - "high"
    NutsEmployeeCredential:
      type: object
      description: The subject of a NutsEmployeeCredential according to the Nuts specs.
      required:
        - "id"
        - "type"
        - "member"
      properties:
        "id":
          $ref: '#/components/schemas/ID'
        "type":
          description: The type of the employee credential subject, must be "Organization".
          example: Organization
          enum: [Organization]
          type: string
        "member":
          $ref: '#/components/schemas/OrganizationMember'
    OrganizationMember:
      type: object
      description: Part of the subject of a NutsEmployeeCredential according to the Nuts specs.
      required:
        - "identifier"
        - "type"
        - "member"
      properties:
        identifier:
          description: Organizational-wide unique identifier of the employee, e.g. a number, user name or e-mail address.
          example: 12345678
          type: string
        roleName:
          description: The role of the employee within the organization.
          type: string
          example: "Verpleegkundige niveau 2"
        type:
          description: The type of the employee credential subject, must be "EmployeeRole".
          example: EmployeeRole
          enum: [EmployeeRole]
          type: string
        member:
          $ref: '#/components/schemas/OrganizationMemberMember'
    OrganizationMemberMember:
      type: object
      description: Part of the subject of a NutsEmployeeCredential according to the Nuts specs.
      properties:
        type:
          description: The type of the employee credential subject, must be "Person".
          example: Person
          enum: [Person]
          type: string
        familyName:
          description: The family name of the employee.
          example: "Jansen"
          type: string
        initials:
          description: The initials of the employee.
          example: "A.B."
          type: string


# Required to make it a valid OpenAPI spec (can be removed when migrating to OAS 3.1.0):
paths:
  /bogus:
    get:
      operationId: bogus
      responses:
        "200":
          description: Bogus